common: &common
  host: localhost
  adapter: postgresql
  username: sample_app
  password: sample_app

development:
  <<: *common
  database: sample_app_development

test:
  <<: *comon
  database: sample_app_test

production:
  <<: *common
  database: sample_app_production
